// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rtl.TVMazeService.Infrastructure.Sql;

namespace Rtl.TVMazeService.Infrastructure.Sql.Migrations
{
    [DbContext(typeof(TVMazeContext))]
    [Migration("20210512204740_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rtl.TVMazeService.Infrastructure.Sql.Models.CastMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CastMembers");
                });

            modelBuilder.Entity("Rtl.TVMazeService.Infrastructure.Sql.Models.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Rtl.TVMazeService.Infrastructure.Sql.Models.ShowCastMember", b =>
                {
                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<int>("CastMemberId")
                        .HasColumnType("int");

                    b.HasKey("ShowId", "CastMemberId");

                    b.HasIndex("CastMemberId");

                    b.ToTable("ShowCastMembers");
                });

            modelBuilder.Entity("Rtl.TVMazeService.Infrastructure.Sql.Models.ShowCastMember", b =>
                {
                    b.HasOne("Rtl.TVMazeService.Infrastructure.Sql.Models.CastMember", "CastMember")
                        .WithMany("ShowCastMembers")
                        .HasForeignKey("CastMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rtl.TVMazeService.Infrastructure.Sql.Models.Show", "Show")
                        .WithMany("ShowCastMembers")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
